/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VrmMaterial {
    name?: string;
    /**
     * This contains shader name.  VRM/MToon, VRM/UnlitTransparentZWrite, and VRM_USE_GLTFSHADER (and legacy materials as Standard, UniGLTF/UniUnlit, VRM/UnlitTexture, VRM/UnlitCutout, VRM/UnlitTransparent) . If VRM_USE_GLTFSHADER is specified, use same index of gltf's material settings
     */
    shader?: string;
    renderQueue?: number;
    floatProperties?: {
        [k: string]: number;
    };
    vectorProperties?: {
        [k: string]: number[];
    };
    textureProperties?: {
        [k: string]: number;
    };
    keywordMap?: {
        [k: string]: boolean;
    };
    tagMap?: {
        [k: string]: string;
    };
}
