import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "HumanBone"
 */
export interface IHumanBone extends IGLTFProperty {
    /**
     * @description "Represents a single glTF node mapped to this humanBone."
     */
    node: IGLTFId;
}
