import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "HumanBones"
 */
export interface IHumanBones extends IGLTFProperty {
    hips: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    spine: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    chest?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    upperChest?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    neck?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    head: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    jaw?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftUpperLeg: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftLowerLeg: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftFoot: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftToes?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightUpperLeg: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightLowerLeg: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightFoot: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightToes?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftShoulder?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftUpperArm: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftLowerArm: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftHand: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightShoulder?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightUpperArm: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightLowerArm: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightHand: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftThumbMetacarpal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftThumbProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftThumbDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftIndexProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftIndexIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftIndexDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftMiddleProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftMiddleIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftMiddleDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftRingProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftRingIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftRingDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftLittleProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftLittleIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    leftLittleDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightThumbMetacarpal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightThumbProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightThumbDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightIndexProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightIndexIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightIndexDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightMiddleProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightMiddleIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightMiddleDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightRingProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightRingIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightRingDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightLittleProximal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightLittleIntermediate?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;

    rightLittleDistal?: IVRMCVrmAnimationHumanoidHumanBonesHumanBone;
}
