import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "LookAt"
 */
export interface ILookAt extends IGLTFProperty {
    /**
     * @description "Represents a single glTF node represents the eye gaze point."
     */
    node: IGLTFId;

    /**
     * @description "The position offset of the origin of the LookAt from the humanoid head bone"
     * @maxItems 3
     * @minItems 3
     */
    offsetFromHeadBone?: number[];
}
