import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Expressions"
 */
export interface IExpressions extends IGLTFProperty {
    /**
     * @description "An object that contains definitions of preset expressions."
     */
    preset?: {
        happy?: IVRMCVrmAnimationExpressionsExpression;
        angry?: IVRMCVrmAnimationExpressionsExpression;
        sad?: IVRMCVrmAnimationExpressionsExpression;
        relaxed?: IVRMCVrmAnimationExpressionsExpression;
        surprised?: IVRMCVrmAnimationExpressionsExpression;
        aa?: IVRMCVrmAnimationExpressionsExpression;
        ih?: IVRMCVrmAnimationExpressionsExpression;
        ou?: IVRMCVrmAnimationExpressionsExpression;
        ee?: IVRMCVrmAnimationExpressionsExpression;
        oh?: IVRMCVrmAnimationExpressionsExpression;
        blink?: IVRMCVrmAnimationExpressionsExpression;
        blinkLeft?: IVRMCVrmAnimationExpressionsExpression;
        blinkRight?: IVRMCVrmAnimationExpressionsExpression;
        neutral?: IVRMCVrmAnimationExpressionsExpression;
    };

    /**
     * @description "An object that contains definitions of custom expressions."
     * @additionalProperties {"$ref":"VRMC_vrm_animation.expressions.expression.schema.json"}
     */
    custom?: Record<string, IVRMCVrmAnimationExpressionsExpression>;
}
