import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "ColliderShape"
 */
export interface IColliderShape extends IGLTFProperty {
    sphere?: { offset?: number[]; radius?: number };

    capsule?: { offset?: number[]; radius?: number; tail?: number[] };
}
