import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "ColliderGroup"
 */
export interface IColliderGroup extends IGLTFProperty {
    /**
     * @description "Name of the ColliderGroup"
     */
    name?: string;

    /**
     * @description "An array of colliders."
     * @minItems 1
     */
    colliders: IGLTFId[];
}
