import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "SpringBoneJoint"
 */
export interface ISpringBoneJoint extends IGLTFProperty {
    /**
     * @description "The node index."
     */
    node: IGLTFId;

    /**
     * @description "The radius of spring sphere."
     * @default 0
     * @minimum 0
     */
    hitRadius?: number;

    /**
     * @description "The force to return to the initial pose."
     * @default 1
     * @minimum 0
     */
    stiffness?: number;

    /**
     * @description "Gravitational acceleration."
     * @default 0
     * @minimum 0
     */
    gravityPower?: number;

    /**
     * @description "The direction of gravity. A gravity other than downward direction also works."
     * @default [0,-1,0]
     * @maxItems 3
     * @minItems 3
     */
    gravityDir?: number[];

    /**
     * @description "Air resistance. Deceleration force."
     * @default 0.5
     * @maximum 1
     * @minimum 0
     */
    dragForce?: number;
}
