import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Collider"
 */
export interface ICollider extends IGLTFProperty {
    /**
     * @description "The node index."
     */
    node: IGLTFId;

    /**
     * @description ""
     */
    shape: IVRMCSpringBoneShape;
}
