import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Spring"
 */
export interface ISpring extends IGLTFProperty {
    /**
     * @description "Name of the Spring"
     */
    name?: string;

    /**
     * @description "Joints of the spring. Except for the first element, a previous joint of the array must be an ancestor of the joint."
     * @minItems 1
     */
    joints: IVRMCSpringBoneJoint[];

    /**
     * @description "Indices of ColliderGroups that detect collision with this spring."
     * @minItems 1
     */
    colliderGroups?: IGLTFId[];

    /**
     * @description "An index of node which is used as a root of center space."
     */
    center?: IGLTFId;
}
