import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMCSpringBone"
 */
export interface IVRMCSpringBone extends IGLTFProperty {
    /**
     * @description "Specification version of VRMC_springBone"
     */
    specVersion: string;

    /**
     * @description "An array of colliders."
     * @minItems 1
     */
    colliders?: IVRMCSpringBoneCollider[];

    /**
     * @description "An array of colliderGroups."
     * @minItems 1
     */
    colliderGroups?: IVRMCSpringBoneColliderGroup[];

    /**
     * @description "An array of springs."
     * @minItems 1
     */
    springs?: IVRMCSpringBoneSpring[];
}
