import type { ITextureInfo } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Shading Shift Texture Info"
 */
export interface IShadingShiftTextureInfo extends ITextureInfo {
    index?: unknown;

    texCoord?: unknown;

    /**
     * @description "The scalar multiplier applied to the texture."
     * @default 1
     */
    scale?: number;
}
