import type { IGLTFProperty, ITextureInfo } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMC_materials_mtoon"
 */
export interface IVRMCMaterialsMtoon extends IGLTFProperty {
    /**
     * @description "Specification version of VRMC_materials_mtoon"
     */
    specVersion: string;

    /**
     * @description "enable depth buffer when `alphaMode` is `BLEND`"
     * @default "false"
     */
    transparentWithZWrite?: boolean;

    /**
     * @description ""
     * @default 0
     * @maximum 9
     * @minimum -9
     */
    renderQueueOffsetNumber?: number;

    /**
     * @description ""
     * @default [1,1,1]
     * @maxItems 3
     * @minItems 3
     */
    shadeColorFactor?: number[];

    /**
     * @description ""
     */
    shadeMultiplyTexture?: ITextureInfo;

    /**
     * @description "Lighting"
     * @default 0
     */
    shadingShiftFactor?: number;

    shadingShiftTexture?: IMtoonShadingShiftTexture;

    /**
     * @description ""
     * @default 0.9
     * @maximum 1
     * @minimum 0
     */
    shadingToonyFactor?: number;

    /**
     * @description ""
     * @default 0.9
     * @maximum 1
     * @minimum 0
     */
    giEqualizationFactor?: number;

    /**
     * @description ""
     * @default [1,1,1]
     * @maxItems 3
     * @minItems 3
     */
    matcapFactor?: number[];

    /**
     * @description "MatCap"
     */
    matcapTexture?: ITextureInfo;

    /**
     * @description "Rim"
     * @default [0,0,0]
     * @maxItems 3
     * @minItems 3
     */
    parametricRimColorFactor?: number[];

    /**
     * @description ""
     */
    rimMultiplyTexture?: ITextureInfo;

    /**
     * @description ""
     * @default 1
     * @maximum 1
     * @minimum 0
     */
    rimLightingMixFactor?: number;

    /**
     * @description ""
     * @default 5
     * @minimum 0
     */
    parametricRimFresnelPowerFactor?: number;

    /**
     * @description ""
     * @default 0
     */
    parametricRimLiftFactor?: number;

    /**
     * @description "Outline"
     * @default "none"
     * @enum ["none","worldCoordinates","screenCoordinates"]
     */
    outlineWidthMode?: "none" | "worldCoordinates" | "screenCoordinates";

    /**
     * @description ""
     * @default 0
     * @minimum 0
     */
    outlineWidthFactor?: number;

    /**
     * @description ""
     */
    outlineWidthMultiplyTexture?: ITextureInfo;

    /**
     * @description ""
     * @default [0,0,0]
     * @maxItems 3
     * @minItems 3
     */
    outlineColorFactor?: number[];

    /**
     * @description ""
     * @default 1
     * @maximum 1
     * @minimum 0
     */
    outlineLightingMixFactor?: number;

    /**
     * @description ""
     */
    uvAnimationMaskTexture?: ITextureInfo;

    /**
     * @description ""
     * @default 0
     */
    uvAnimationScrollXSpeedFactor?: number;

    /**
     * @description ""
     * @default 0
     */
    uvAnimationScrollYSpeedFactor?: number;

    /**
     * @description ""
     * @default 0
     */
    uvAnimationRotationSpeedFactor?: number;
}
