/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.humanoid"
 */
export interface IVrmHumanoid {
    humanBones?: IVrmHumanoidBone[];

    /**
     * @description "Unity's HumanDescription.armStretch"
     */
    armStretch?: number;

    /**
     * @description "Unity's HumanDescription.legStretch"
     */
    legStretch?: number;

    /**
     * @description "Unity's HumanDescription.upperArmTwist"
     */
    upperArmTwist?: number;

    /**
     * @description "Unity's HumanDescription.lowerArmTwist"
     */
    lowerArmTwist?: number;

    /**
     * @description "Unity's HumanDescription.upperLegTwist"
     */
    upperLegTwist?: number;

    /**
     * @description "Unity's HumanDescription.lowerLegTwist"
     */
    lowerLegTwist?: number;

    /**
     * @description "Unity's HumanDescription.feetSpacing"
     */
    feetSpacing?: number;

    /**
     * @description "Unity's HumanDescription.hasTranslationDoF"
     */
    hasTranslationDoF?: boolean;
}
