/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.humanoid.bone"
 */
export interface IVrmHumanoidBone {
    /**
     * @description "Human bone name."
     * @enum ["hips","leftUpperLeg","rightUpperLeg","leftLowerLeg","rightLowerLeg","leftFoot","rightFoot","spine","chest","neck","head","leftShoulder","rightShoulder","leftUpperArm","rightUpperArm","leftLowerArm","rightLowerArm","leftHand","rightHand","leftToes","rightToes","leftEye","rightEye","jaw","leftThumbProximal","leftThumbIntermediate","leftThumbDistal","leftIndexProximal","leftIndexIntermediate","leftIndexDistal","leftMiddleProximal","leftMiddleIntermediate","leftMiddleDistal","leftRingProximal","leftRingIntermediate","leftRingDistal","leftLittleProximal","leftLittleIntermediate","leftLittleDistal","rightThumbProximal","rightThumbIntermediate","rightThumbDistal","rightIndexProximal","rightIndexIntermediate","rightIndexDistal","rightMiddleProximal","rightMiddleIntermediate","rightMiddleDistal","rightRingProximal","rightRingIntermediate","rightRingDistal","rightLittleProximal","rightLittleIntermediate","rightLittleDistal","upperChest"]
     */
    bone?:
        | "hips"
        | "leftUpperLeg"
        | "rightUpperLeg"
        | "leftLowerLeg"
        | "rightLowerLeg"
        | "leftFoot"
        | "rightFoot"
        | "spine"
        | "chest"
        | "neck"
        | "head"
        | "leftShoulder"
        | "rightShoulder"
        | "leftUpperArm"
        | "rightUpperArm"
        | "leftLowerArm"
        | "rightLowerArm"
        | "leftHand"
        | "rightHand"
        | "leftToes"
        | "rightToes"
        | "leftEye"
        | "rightEye"
        | "jaw"
        | "leftThumbProximal"
        | "leftThumbIntermediate"
        | "leftThumbDistal"
        | "leftIndexProximal"
        | "leftIndexIntermediate"
        | "leftIndexDistal"
        | "leftMiddleProximal"
        | "leftMiddleIntermediate"
        | "leftMiddleDistal"
        | "leftRingProximal"
        | "leftRingIntermediate"
        | "leftRingDistal"
        | "leftLittleProximal"
        | "leftLittleIntermediate"
        | "leftLittleDistal"
        | "rightThumbProximal"
        | "rightThumbIntermediate"
        | "rightThumbDistal"
        | "rightIndexProximal"
        | "rightIndexIntermediate"
        | "rightIndexDistal"
        | "rightMiddleProximal"
        | "rightMiddleIntermediate"
        | "rightMiddleDistal"
        | "rightRingProximal"
        | "rightRingIntermediate"
        | "rightRingDistal"
        | "rightLittleProximal"
        | "rightLittleIntermediate"
        | "rightLittleDistal"
        | "upperChest";

    /**
     * @description "Reference node index"
     */
    node?: number;

    /**
     * @description "Unity's HumanLimit.useDefaultValues"
     */
    useDefaultValues?: boolean;

    /**
     * @description "Unity's HumanLimit.min"
     */
    min?: { x?: number; y?: number; z?: number };

    /**
     * @description "Unity's HumanLimit.max"
     */
    max?: { x?: number; y?: number; z?: number };

    /**
     * @description "Unity's HumanLimit.center"
     */
    center?: { x?: number; y?: number; z?: number };

    /**
     * @description "Unity's HumanLimit.axisLength"
     */
    axisLength?: number;
}
