/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.meta"
 */
export interface IVrmMeta {
    /**
     * @description "Title of VRM model"
     */
    title?: string;

    /**
     * @description "Version of VRM model"
     */
    version?: string;

    /**
     * @description "Author of VRM model"
     */
    author?: string;

    /**
     * @description "Contact Information of VRM model author"
     */
    contactInformation?: string;

    /**
     * @description "Reference of VRM model"
     */
    reference?: string;

    /**
     * @description "Thumbnail of VRM model"
     */
    texture?: number;

    /**
     * @description "A person who can perform with this avatar"
     * @enum ["OnlyAuthor","ExplicitlyLicensedPerson","Everyone"]
     */
    allowedUserName?: "OnlyAuthor" | "ExplicitlyLicensedPerson" | "Everyone";

    /**
     * @description "Permission to perform violent acts with this avatar"
     * @enum ["Disallow","Allow"]
     */
    violentUssageName?: "Disallow" | "Allow";

    /**
     * @description "Permission to perform sexual acts with this avatar"
     * @enum ["Disallow","Allow"]
     */
    sexualUssageName?: "Disallow" | "Allow";

    /**
     * @description "For commercial use"
     * @enum ["Disallow","Allow"]
     */
    commercialUssageName?: "Disallow" | "Allow";

    /**
     * @description "If there are any conditions not mentioned above, put the URL link of the license document here."
     */
    otherPermissionUrl?: string;

    /**
     * @description "License type"
     * @enum ["Redistribution_Prohibited","CC0","CC_BY","CC_BY_NC","CC_BY_SA","CC_BY_NC_SA","CC_BY_ND","CC_BY_NC_ND","Other"]
     */
    licenseName?:
        | "Redistribution_Prohibited"
        | "CC0"
        | "CC_BY"
        | "CC_BY_NC"
        | "CC_BY_SA"
        | "CC_BY_NC_SA"
        | "CC_BY_ND"
        | "CC_BY_NC_ND"
        | "Other";

    /**
     * @description "If “Other” is selected, put the URL link of the license document here."
     */
    otherLicenseUrl?: string;
}
