/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.firstperson.meshannotation"
 */
export interface IVrmFirstpersonMeshannotation {
    mesh?: number;

    firstPersonFlag?: string;
}
