/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.material"
 */
export interface IVrmMaterial {
    name?: string;

    /**
     * @description "This contains shader name.  VRM/MToon, VRM/UnlitTransparentZWrite, and VRM_USE_GLTFSHADER (and legacy materials as Standard, UniGLTF/UniUnlit, VRM/UnlitTexture, VRM/UnlitCutout, VRM/UnlitTransparent) . If VRM_USE_GLTFSHADER is specified, use same index of gltf's material settings"
     */
    shader?: string;

    renderQueue?: number;

    /**
     * @additionalProperties {"type":"number"}
     */
    floatProperties?: Record<string, number>;

    /**
     * @additionalProperties {"type":"array","items":{"type":"number"}}
     */
    vectorProperties?: Record<string, number[]>;

    /**
     * @additionalProperties {"type":"integer"}
     */
    textureProperties?: Record<string, number>;

    /**
     * @additionalProperties {"type":"boolean"}
     */
    keywordMap?: Record<string, boolean>;

    /**
     * @additionalProperties {"type":"string"}
     */
    tagMap?: Record<string, string>;
}
