/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.blendshape.bind"
 */
export interface IVrmBlendshapeBind {
    /**
     * @minimum 0
     */
    mesh?: number;

    /**
     * @minimum 0
     */
    index?: number;

    /**
     * @description "SkinnedMeshRenderer.SetBlendShapeWeight"
     * @maximum 100
     * @minimum 0
     */
    weight?: number;
}
