/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.secondaryanimation.collidergroup"
 */
export interface IVrmSecondaryanimationCollidergroup {
    /**
     * @description "The node of the collider group for setting up collision detections."
     */
    node?: number;

    colliders?: { offset?: { x?: number; y?: number; z?: number }; radius?: number }[];
}
