/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.secondaryanimation.spring"
 */
export interface IVrmSecondaryanimationSpring {
    /**
     * @description "Annotation comment"
     */
    comment?: string;

    /**
     * @description "The resilience of the swaying object (the power of returning to the initial pose)."
     */
    stiffiness?: number;

    /**
     * @description "The strength of gravity."
     */
    gravityPower?: number;

    /**
     * @description "The direction of gravity. Set (0, -1, 0) for simulating the gravity. Set (1, 0, 0) for simulating the wind."
     */
    gravityDir?: { x?: number; y?: number; z?: number };

    /**
     * @description "The resistance (deceleration) of automatic animation."
     */
    dragForce?: number;

    /**
     * @description "The reference point of a swaying object can be set at any location except the origin. When implementing UI moving with warp, the parent node to move with warp can be specified if you don't want to make the object swaying with warp movement."
     */
    center?: number;

    /**
     * @description "The radius of the sphere used for the collision detection with colliders."
     */
    hitRadius?: number;

    /**
     * @description "Specify the node index of the root bone of the swaying object."
     */
    bones?: number[];

    /**
     * @description "Specify the index of the collider group for collisions with swaying objects."
     */
    colliderGroups?: number[];
}
