/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.firstperson.degreemap"
 */
export interface IVrmFirstpersonDegreemap {
    /**
     * @description "None linear mapping params. time, value, inTangent, outTangent"
     */
    curve?: number[];

    /**
     * @description "Look at input clamp range degree."
     */
    xRange?: number;

    /**
     * @description "Look at map range degree from xRange."
     */
    yRange?: number;
}
