/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.firstperson"
 */
export interface IVrmFirstperson {
    /**
     * @description "The bone whose rendering should be turned off in first-person view. Usually Head is specified."
     */
    firstPersonBone?: number;

    /**
     * @description "The target position of the VR headset in first-person view. It is assumed that an offset from the head bone to the VR headset is added."
     */
    firstPersonBoneOffset?: { x?: number; y?: number; z?: number };

    /**
     * @description "Switch display / undisplay for each mesh in first-person view or the others."
     */
    meshAnnotations?: IVrmFirstpersonMeshannotation[];

    /**
     * @description "Eye controller mode."
     * @enum ["Bone","BlendShape"]
     */
    lookAtTypeName?: "Bone" | "BlendShape";

    lookAtHorizontalInner?: IVrmFirstpersonDegreemap;

    lookAtHorizontalOuter?: IVrmFirstpersonDegreemap;

    lookAtVerticalDown?: IVrmFirstpersonDegreemap;

    lookAtVerticalUp?: IVrmFirstpersonDegreemap;
}
