/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm.blendshape.group"
 */
export interface IVrmBlendshapeGroup {
    /**
     * @description "Expression name"
     */
    name?: string;

    /**
     * @description "Predefined Expression name"
     * @enum ["unknown","neutral","a","i","u","e","o","blink","joy","angry","sorrow","fun","lookup","lookdown","lookleft","lookright","blink_l","blink_r"]
     */
    presetName?:
        | "unknown"
        | "neutral"
        | "a"
        | "i"
        | "u"
        | "e"
        | "o"
        | "blink"
        | "joy"
        | "angry"
        | "sorrow"
        | "fun"
        | "lookup"
        | "lookdown"
        | "lookleft"
        | "lookright"
        | "blink_l"
        | "blink_r";

    /**
     * @description "Low level blendshape references."
     */
    binds?: IVrmBlendshapeBind[];

    /**
     * @description "Material animation references."
     */
    materialValues?: IVrmBlendshapeMaterialbind[];

    /**
     * @description "0 or 1. Do not allow an intermediate value. Value should rounded"
     */
    isBinary?: boolean;
}
