/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "vrm"
 */
export interface IVrm {
    /**
     * @description "Version of exporter that vrm created. UniVRM-0.46"
     */
    exporterVersion?: string;

    /**
     * @description "Version of VRM specification. 0.0"
     */
    specVersion?: string;

    meta?: IVrmMeta;

    humanoid?: IVrmHumanoid;

    firstPerson?: IVrmFirstperson;

    blendShapeMaster?: IVrmBlendshape;

    secondaryAnimation?: IVrmSecondaryanimation;

    materialProperties?: IVrmMaterial[];
}
