import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMCSpringBoneExtendedCollider"
 */
export interface IVRMCSpringBoneExtendedCollider extends IGLTFProperty {
    /**
     * @description "Specification version of VRMC_springBone_extended_collider."
     */
    specVersion: string;

    /**
     * @description "The shape of the collider."
     */
    shape?: IVRMCSpringBoneExtendedColliderShape;
}
