import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "ExtendedColliderShape"
 */
export interface IExtendedColliderShape extends IGLTFProperty {
    sphere?: { offset?: number[]; radius?: number; inside?: boolean };

    capsule?: { offset?: number[]; radius?: number; tail?: number[]; inside?: boolean };

    plane?: { offset?: number[]; normal?: number[] };
}
