import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "MaterialColorBind"
 */
export interface IMaterialColorBind extends IGLTFProperty {
    /**
     * @description "target material"
     */
    material: IGLTFId;

    /**
     * @enum ["color","emissionColor","shadeColor","matcapColor","rimColor","outlineColor"]
     */
    type: "color" | "emissionColor" | "shadeColor" | "matcapColor" | "rimColor" | "outlineColor";

    /**
     * @description "target color"
     * @maxItems 4
     * @minItems 4
     */
    targetValue: number[];
}
