import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "MeshAnnotation"
 */
export interface IMeshAnnotation extends IGLTFProperty {
    /**
     * @description "The index of the node that attached to target mesh."
     */
    node: IGLTFId;

    /**
     * @description "How the camera interprets the mesh."
     * @enum ["auto","both","thirdPersonOnly","firstPersonOnly"]
     */
    type: "auto" | "both" | "thirdPersonOnly" | "firstPersonOnly";
}
