/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "HumanBones"
 */
export interface IHumanBones {
    hips: IVRMCVrmHumanoidHumanBonesHumanBone;

    spine: IVRMCVrmHumanoidHumanBonesHumanBone;

    chest?: IVRMCVrmHumanoidHumanBonesHumanBone;

    upperChest?: IVRMCVrmHumanoidHumanBonesHumanBone;

    neck?: IVRMCVrmHumanoidHumanBonesHumanBone;

    head: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftEye?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightEye?: IVRMCVrmHumanoidHumanBonesHumanBone;

    jaw?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftUpperLeg: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftLowerLeg: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftFoot: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftToes?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightUpperLeg: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightLowerLeg: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightFoot: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightToes?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftShoulder?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftUpperArm: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftLowerArm: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftHand: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightShoulder?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightUpperArm: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightLowerArm: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightHand: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftThumbMetacarpal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftThumbProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftThumbDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftIndexProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftIndexIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftIndexDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftMiddleProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftMiddleIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftMiddleDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftRingProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftRingIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftRingDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftLittleProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftLittleIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    leftLittleDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightThumbMetacarpal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightThumbProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightThumbDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightIndexProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightIndexIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightIndexDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightMiddleProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightMiddleIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightMiddleDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightRingProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightRingIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightRingDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightLittleProximal?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightLittleIntermediate?: IVRMCVrmHumanoidHumanBonesHumanBone;

    rightLittleDistal?: IVRMCVrmHumanoidHumanBonesHumanBone;
}
