import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Expression"
 */
export interface IExpression extends IGLTFProperty {
    /**
     * @description "Specify a morph target"
     * @minItems 1
     */
    morphTargetBinds?: IVRMCVrmExpressionsExpressionMorphTargetBind[];

    /**
     * @description "Material color animation references"
     * @minItems 1
     */
    materialColorBinds?: IVRMCVrmExpressionsExpressionMaterialColorBind[];

    /**
     * @description "Texture transform animation references"
     * @minItems 1
     */
    textureTransformBinds?: IVRMCVrmExpressionsExpressionTextureTransformBind[];

    /**
     * @description "A value greater than 0.5 is 1.0, otherwise 0.0"
     * @default false
     */
    isBinary?: boolean;

    /**
     * @description "Override values of Blink expressions when this Expression is enabled"
     * @default "none"
     * @enum ["none","block","blend"]
     */
    overrideBlink?: "none" | "block" | "blend";

    /**
     * @description "Override values of LookAt expressions when this Expression is enabled"
     * @default "none"
     * @enum ["none","block","blend"]
     */
    overrideLookAt?: "none" | "block" | "blend";

    /**
     * @description "Override values of Mouth expressions when this Expression is enabled"
     * @default "none"
     * @enum ["none","block","blend"]
     */
    overrideMouth?: "none" | "block" | "blend";
}
