import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "LookAtRangeMap"
 */
export interface ILookAtRangeMap extends IGLTFProperty {
    /**
     * @description "Yaw and pitch angles  ( degrees )  between the head bone forward vector and the eye gaze LookAt vector"
     * @maximum 180
     * @minimum 0
     */
    inputMaxValue?: number;

    /**
     * @description "Degree for type.bone, Weight for type.expressions"
     */
    outputScale?: number;
}
