import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "TextureTransformBind"
 */
export interface ITextureTransformBind extends IGLTFProperty {
    /**
     * @description "target material"
     */
    material: IGLTFId;

    /**
     * @description "uv scaling for TEXCOORD_0"
     * @default [1,1]
     * @maxItems 2
     * @minItems 2
     */
    scale?: number[];

    /**
     * @description "uv offset for TEXCOORD_0"
     * @default [0,0]
     * @maxItems 2
     * @minItems 2
     */
    offset?: number[];
}
