import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "FirstPerson"
 */
export interface IFirstPerson extends IGLTFProperty {
    /**
     * @description "Mesh rendering annotation for cameras."
     * @minItems 1
     */
    meshAnnotations?: IVRMCVrmFirstPersonMeshAnnotation[];
}
