import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Expressions"
 */
export interface IExpressions extends IGLTFProperty {
    /**
     * @description "Preset expressions"
     */
    preset?: {
        happy?: IVRMCVrmExpressionsExpression;
        angry?: IVRMCVrmExpressionsExpression;
        sad?: IVRMCVrmExpressionsExpression;
        relaxed?: IVRMCVrmExpressionsExpression;
        surprised?: IVRMCVrmExpressionsExpression;
        aa?: IVRMCVrmExpressionsExpression;
        ih?: IVRMCVrmExpressionsExpression;
        ou?: IVRMCVrmExpressionsExpression;
        ee?: IVRMCVrmExpressionsExpression;
        oh?: IVRMCVrmExpressionsExpression;
        blink?: IVRMCVrmExpressionsExpression;
        blinkLeft?: IVRMCVrmExpressionsExpression;
        blinkRight?: IVRMCVrmExpressionsExpression;
        lookUp?: IVRMCVrmExpressionsExpression;
        lookDown?: IVRMCVrmExpressionsExpression;
        lookLeft?: IVRMCVrmExpressionsExpression;
        lookRight?: IVRMCVrmExpressionsExpression;
        neutral?: IVRMCVrmExpressionsExpression;
    };

    /**
     * @description "Custom expressions"
     * @additionalProperties {"$ref":"VRMC_vrm.expressions.expression.schema.json"}
     */
    custom?: Record<string, IVRMCVrmExpressionsExpression>;
}
