import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "MorphTargetBind"
 */
export interface IMorphTargetBind extends IGLTFProperty {
    /**
     * @description "The index of the node that attached to target mesh."
     */
    node: IGLTFId;

    /**
     * @description "The index of the morph target in the mesh."
     */
    index: IGLTFId;

    /**
     * @description "The weight value of target morph target."
     */
    weight: number;
}
