import type { IGLTFProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Meta"
 */
export interface IMeta extends IGLTFProperty {
    /**
     * @description "The name of the model"
     * @minLength 1
     */
    name: string;

    /**
     * @description "The version of the model"
     */
    version?: string;

    /**
     * @description "Authors of the model"
     * @minItems 1
     */
    authors: string[];

    /**
     * @description "An information that describes the copyright of the model"
     */
    copyrightInformation?: string;

    /**
     * @description "An information that describes the contact information of the author"
     */
    contactInformation?: string;

    /**
     * @description "References / original works of the model"
     * @minItems 1
     */
    references?: string[];

    /**
     * @description "Third party licenses of the model, if required. You can use line breaks"
     */
    thirdPartyLicenses?: string;

    /**
     * @description "The index to the thumbnail image of the model in gltf.images"
     */
    thumbnailImage?: IGLTFId;

    /**
     * @description "A URL towards the license document this model refers to"
     */
    licenseUrl: string;

    /**
     * @description "A person who can perform as an avatar with this model"
     * @default "onlyAuthor"
     * @enum ["onlyAuthor","onlySeparatelyLicensedPerson","everyone"]
     */
    avatarPermission?: "onlyAuthor" | "onlySeparatelyLicensedPerson" | "everyone";

    /**
     * @description "A flag that permits to use this model in excessively violent contents"
     * @default false
     */
    allowExcessivelyViolentUsage?: boolean;

    /**
     * @description "A flag that permits to use this model in excessively sexual contents"
     * @default false
     */
    allowExcessivelySexualUsage?: boolean;

    /**
     * @description "An option that permits to use this model in commercial products"
     * @default "personalNonProfit"
     * @enum ["personalNonProfit","personalProfit","corporation"]
     */
    commercialUsage?: "personalNonProfit" | "personalProfit" | "corporation";

    /**
     * @description "A flag that permits to use this model in political or religious contents"
     * @default false
     */
    allowPoliticalOrReligiousUsage?: boolean;

    /**
     * @description "A flag that permits to use this model in contents contain anti-social activities or hate speeches"
     * @default false
     */
    allowAntisocialOrHateUsage?: boolean;

    /**
     * @description "An option that forces or abandons to display the credit of this model"
     * @default "required"
     * @enum ["required","unnecessary"]
     */
    creditNotation?: "required" | "unnecessary";

    /**
     * @description "A flag that permits to redistribute this model"
     * @default false
     */
    allowRedistribution?: boolean;

    /**
     * @description "An option that controls the condition to modify this model"
     * @default "prohibited"
     * @enum ["prohibited","allowModification","allowModificationRedistribution"]
     */
    modification?: "prohibited" | "allowModification" | "allowModificationRedistribution";

    /**
     * @description "Describe the URL links of other license"
     */
    otherLicenseUrl?: string;
}
