import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "LookAt"
 */
export interface ILookAt extends IGLTFProperty {
    /**
     * @description "The origin of LookAt. Position offset from the head bone"
     * @maxItems 3
     * @minItems 3
     */
    offsetFromHeadBone?: number[];

    /**
     * @enum ["bone","expression"]
     */
    type?: "bone" | "expression";

    rangeMapHorizontalInner?: IVRMCVrmLookAtRangeMap;

    rangeMapHorizontalOuter?: IVRMCVrmLookAtRangeMap;

    rangeMapVerticalDown?: IVRMCVrmLookAtRangeMap;

    rangeMapVerticalUp?: IVRMCVrmLookAtRangeMap;
}
