import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMCVrm"
 */
export interface IVRMCVrm extends IGLTFProperty {
    /**
     * @description "Specification version of VRMC_vrm"
     */
    specVersion: string;

    meta: IVRMCVrmMeta;

    humanoid: IVRMCVrmHumanoid;

    firstPerson?: IVRMCVrmFirstPerson;

    lookAt?: IVRMCVrmLookAt;

    expressions?: IVRMCVrmExpressions;
}
