import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMC_materials_hdr_emissiveMultiplier"
 */
export interface IVRMCMaterialsHdrEmissiveMultiplier extends IGLTFProperty {
    /**
     * @description "A multiplier for emissiveFactor"
     * @default 1
     * @minimum 0
     */
    emissiveMultiplier: number;
}
