import type { IGLTFChildOfRootProperty, IGLTFId } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "Aim Constraint"
 */
export interface IAimConstraint extends IGLTFChildOfRootProperty {
    /**
     * @description "The index of the node constrains the node."
     */
    source: IGLTFId;

    /**
     * @description "The aim axis of the constraint."
     * @enum ["PositiveX","NegativeX","PositiveY","NegativeY","PositiveZ","NegativeZ"]
     */
    aimAxis: "PositiveX" | "NegativeX" | "PositiveY" | "NegativeY" | "PositiveZ" | "NegativeZ";

    /**
     * @description "The weight of the constraint."
     * @default 1
     * @maximum 1
     * @minimum 0
     */
    weight?: number;
}
