import type { IGLTFProperty } from "@yamayuski/babylon-vrm-core";

/**
 * THIS SCHEMA TYPE DEFINITION FILE IS AUTO-GENERATED.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, edit the JSON schema and run the script to regenerate.
 *
 * Source JSON Schema: "VRMC_node_constraint extension"
 */
export interface IVRMCNodeConstraintextension extends IGLTFProperty {
    /**
     * @description "Specification version of VRMC_node_constraint"
     */
    specVersion: string;

    constraint: IVRMCNodeConstraintConstraint;
}
